apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y25ip3y1r-java-quarkus
  janus-idp.io/tekton: y25ip3y1r-java-quarkus
  backstage.io/kubernetes-id: y25ip3y1r-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y25ip3y1r-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
